version: "3.1"

services:
  redis:
    image: redis
    privileged: true
    ports:
      - 6379:6379
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nikolay
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db
  backend:
    build: ./send_email
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "
      python manage.py migrate &&
      gunicorn send_email.wsgi -b 0.0.0.0:8080 &&
      celery -A send_email worker -l info
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend